### PR TITLE
started work on new animation

### PR DESCRIPTION
**Pull request by keraJLi**
Based on p5js
Should probably import it better, currently done through inline script elements

### CODE REVIEW

**Comment by keraJLi** [comment]
Move / Opacity while scrolling is still missing

**Comment by keraJLi** [comment]
Also:  the deployment does not work because of the weird import of p5js

Content-Security-Policy: Die Einstellungen der Seite haben die Anwendung eines Scripts (script-src-elem) auf https://cdn.jsdelivr.net/npm/p5@1.9.3/lib/p5.js blockiert, da es gegen folgende Direktive verstößt: "script-src-elem 'none'"

**Comment by optzGuitar** [comment]
could you check if you see a difference in lighthouse? Otherwise it might not be worth fixing the deployment.

**Comment by keraJLi** [comment]
> could you check if you see a difference in lighthouse? Otherwise it might not be worth fixing the deployment.

The new animation has a 95 performance score on pagespeed insights, the old one merely 62:

Old:
```
Total Blocking Time: 10.180 ms
Speed Index: 8,6 s
```
New:
```
Total Blocking Time: 250 ms
Speed Index: 2,7 s
```

Also the new one looks better ^^

**Comment by optzGuitar** [comment]
ok lighthouse is very happy with it and I think it looks stunning!
Could you please make sure to center it on mobile? It is offset to the left at least on my phone.

**Comment by keraJLi** [comment]
- [ ] Mobile: Make animation take over whole screen
  - Either scroll up/down
  - Scale noise along x/y axis, adapt gravity calculation (could be a lot of effort)

**Pull request merged**
